title: Baptiste Wijas
description: Postdoctoral Researcher - University of Miami
site_title: '@BaptisteWij - Baptiste Wijas'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: BaptisteWij
blog_url: https://scholar.google.com/citations?user=dNPdbJcAAAAJ&hl=en
email: bwijas@gmail.com
twitter_username: BapsWijas


# absolute or relative
profile_picture: assets/images/IMG_0568.JPG

# Google Analytics ID
google_analytics: 